title: Open Identity Platform
description: Access management, identity management, user-managed access, directory services, and an identity gateway, designed and built as a single, unified platform.
avatar: https://avatars3.githubusercontent.com/u/30845478?s=200&v=4
theme: jekyll-theme-slate
repo_url: https://github.com/OpenIdentityPlatform
image: https://avatars3.githubusercontent.com/u/30845478?s=200&v=4

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
