-
  name: 'OpenDJ'
  link: 'https://github.com/OpenIdentityPlatform/OpenDJ/'
  short_descritopn: 'Open Directory Services'
  description: 'OpenDJ is an LDAPv3 compliant directory service, which has been developed for the Java platform and provides a high performance, highly available, and secure store for identities, that are managed by your organization. Its easy installation process, combined with the power of the Java platform makes OpenDJ the simplest, fastest directory to deploy and manage.'
  details_link: '/opendj'
  release_link: 'https://github.com/OpenIdentityPlatform/OpenDJ/releases'
-
  name: 'OpenAM'
  link: 'https://github.com/OpenIdentityPlatform/OpenAM/'
  short_descritopn: 'Open Access Management'
  description: 'Open Access Management (OpenAM) is an access management solution that includes Authentication, SSO, Authorization, Federation, Entitlements, and Web Services Security.'
  details_link: '/openam'
  release_link: 'https://github.com/OpenIdentityPlatform/OpenAM/releases'
-
  name: 'OpenIG'
  link: 'https://github.com/OpenIdentityPlatform/OpenIG/'
  short_descritopn: 'Open Identity Gateway'
  description: 'Open Identity Gateway (OpenIG) is a high-performance reverse proxy server with specialized session management and credential replay functionality.'
  details_link: '/openig'
  release_link: 'https://github.com/OpenIdentityPlatform/OpenIG/releases'
-
  name: 'OpenICF'
  link: 'https://github.com/OpenIdentityPlatform/OpenICF/'
  short_descritopn: 'Open Identity Connector Framework'
  description: 'Open Identity Connector Framework (OpenICF) provides interoperability between identity, compliance and risk management solutions. An OpenICF Connector enables provisioning software, such as OpenIDM, to manage the identities that are maintained by a specific identity provider.'
  details_link: '/openicf'
  release_link: 'https://github.com/OpenIdentityPlatform/OpenICF/releases'
-
  name: 'OpenIDM'
  link: 'https://github.com/OpenIdentityPlatform/OpenIDM/'
  short_descritopn: 'Open Identity Management'
  description: 'Open Identity Management (OpenIDM) is an open standards-based Identity Management, Provisioning, and Compliance solution. Provisioning users, devices, and things is a repetitive and potentially time-consuming task that has a significant impact on security and user access. '
  details_link: '/openidm'
  release_link: 'https://github.com/OpenIdentityPlatform/OpenIDM/releases'

