-
  name: 'OpenAM'
  link: 'https://github.com/OpenIdentityPlatform/OpenAM/'
  description: 'Open Access Management (OpenAM) is an access management solution that includes Authentication, SSO, Authorization, Federation, Entitlements and Web Services Security.'
  details_link: '/openam'
-
  name: 'OpenDJ'
  link: 'https://github.com/OpenIdentityPlatform/OpenDJ/'
  description: 'OpenDJ is an LDAPv3 compliant directory service, which has been developed for the Java platform, provides a high performance, highly available, and secure store for identities, that managed by your organization. Its easy installation process, combined with the power of the Java platform makes OpenDJ the simplest, fastest directory to deploy and manage.'
  details_link: '/opendj'
-
  name: 'OpenIG'
  link: 'https://github.com/OpenIdentityPlatform/OpenIG/'
  description: 'Open Identity Gateway (OpenIG) is a high-performance reverse proxy server with specialized session management and credential replay functionality.'
  details_link: '/openig'
-
  name: 'OpenICF'
  link: 'https://github.com/OpenIdentityPlatform/OpenICF/'
  description: 'Open Identity Connector Framework (OpenICF) provides interoperability between identity, compliance and risk management solutions. An OpenICF Connector enables provisioning software, such as OpenIDM, to manage the identities that are maintained by a specific identity provider.'
  details_link: 'https://github.com/OpenIdentityPlatform/OpenICF/blob/master/README.md'
-
  name: 'OpenIDM'
  link: 'https://github.com/OpenIdentityPlatform/OpenIDM/'
  description: 'Open Identity Management (OpenIDM) is an open standards based Identity Management, Provisioning and Compliance solution. Provisioning users, devices, and things is a repetitive and potentially time-consuming task that has a significant impact on security and user access. Ensuring the right access to the right service (or user, or device) is the essential step in Identity Management. It’s critical for you to correctly manage roles and entitlements assigned to users, devices, or things, based on your organizational need and structure (such as job function, title, and geography) and assign and remove entitlements and resources consistently and rapidly. provided.'
  details_link: 'https://github.com/OpenIdentityPlatform/OpenIDM/blob/master/README.md'
